baseURL = ''
languageCode = 'en-us'
title = 'Velar | Modular Interiors and Construction Innovations'
theme = 'TenSketch-2025'
[params]
favicon = '/favicon1.png'
description = 'Velar specializes in modular interiors, infrastructure solutions, and construction projects. From designing timeless interiors to redefining exteriors with research-driven practices, we deliver unmatched quality and value.'
keywords = 'Velar Infra Projects LLP, interior designers, interior designers, modular interiors, infrastructure solutions, custom interiors, innovative construction, residential and corporate interiors, infrastructure development, exterior solutions, Construction company, builders, turnkey projects'
author = 'Balachandiran - TenSketch'
logo = '/images/VELAR-LOGO-h.png'
og_image = '/ogimage.jpg'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[asset]
  # Enable Hugo pipes for SCSS
  enable = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About Us"
    url = "/about-us"
    weight = 2
  [[menu.main]]
    name = "Contact Us"
    url = "#contact-us"
    weight = 3


  [[menu.footer]]
    name = "Terms & Conditions"
    url = "/terms-and-conditions"
    weight = 1
